---
title: "project101"
output: html_document
date: "2022-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ezids)
library(ggplot2)
library(plyr)
library(corrplot)
library(caTools)
```

## SMART QUESTION

### Does the age at which adolescents start engaging in "deviant" behaviors predict their interpersonal, physical, and mental well-being? Furthermore, how does race influence interpersonal, physical, and mental well-being?


```{r cars}
dataset = read.csv("/Users/carriemagee/Downloads/sadc_df.csv")
myvars <- c("Age_Alc", "Age_Weed","multiple_partners","physical_activity","Hrs_Sleep","age_sex","race","sex","fight","suicide")
data <- dataset[myvars]
data <- data[data$age_sex != 0,] 
```


```{r}
data$fight <- recode(data$fight, '0' = 1, '1' = 0)
data$suicide <- recode(data$suicide, '0' = 1, '1' = 0)
```


## Including Plots

```{r}
summary(data)

data$sex <- as.factor(data$sex)
data$race <- as.factor(data$race)

data$suicide1 <- as.factor(data$suicide)
data$fight1 <- as.factor(data$fight)

str(data)
```


You can also embed plots, for example:

```{r}
data$fight
str(data$fight1)
```


```{r}
split <- sample.split(data, SplitRatio = 0.8)
split
train <- subset(data, split == "TRUE")
test <- subset(data, split == "FALSE")
```

```{r}
mod<-glm(formula = fight1 ~ Age_Weed + Age_Alc + age_sex + race , family = "binomial", data = train)
summary(mod)

res <- predict(mod,test,type="response")
res <- predict(mod, train, type="response")

cf <- table(Actual_Value=train$fight1, Predicted_value = res >0.5)
xkabledply(cf, title = "Confusion matrix from Logit Model" )
accuracy <- (cf[[1,1]]+cf[[2,2]])/sum(cf)
accuracy
```


```{r}
mod2<-glm(formula = suicide1 ~ Age_Weed + Age_Alc + age_sex + race, family = "binomial", data = train)
summary(mod2)

res <- predict(mod2,test,type="response")
res <- predict(mod2, train, type="response")

cf2 <- table(Actual_Value=train$suicide1, Predicted_value = res >0.5)
xkabledply(cf2, title = "Confusion matrix from Logit Model" )
accuracy <- (cf2[[1,1]]+cf2[[2,2]])/sum(cf2)
accuracy
```

```{r}
data$race <- as.factor(data$race)
lm <- lm(Hrs_Sleep ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm)
xkabledply(lm, title = paste("Model :", format(formula(lm)) ) )
xkablevif(lm)
```

```{r}
lm1 <- lm(multiple_partners ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm1)
xkabledply(lm1, title = paste("Model :", format(formula(lm1)) ) )
```

```{r}
lm2 <- lm(physical_activity ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm2)
xkabledply(lm2, title = paste("Model :", format(formula(lm2)) ) )
```