---
title: "project101"
output: html_document
date: "2022-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ezids)
library(ggplot2)
library(dplyr)
library(corrplot)
```

## SMART QUESTION

### Does the age at which adolescents start engaging in "deviant" behaviors predict their interpersonal, physical, and mental well-being? Furthermore, how does race influence interpersonal, physical, and mental well-being?


```{r cars}
dataset = read.csv("sadc_df.csv")
# select variables v1, v2, v3
myvars <- c("Age_Alc", "Age_Weed","multiple_partners","physical_activity","Hrs_Sleep","age_sex","race","gender","fight","suicide")
data <- dataset[myvars]
data <- data[data$age_sex != 0,]

data$race <- as.factor(data$race)
data$gender <- as.factor(data$gender)
data$fight <- as.factor(data$fight)
data$suicide <- as.factor(data$suicide)

```

```{r}
# Age when they started drinking
#data$Age_Alc <- as.factor(data$Age_Alc)
data_age_alc <- data %>% 
              group_by(Age_Alc) %>% 
              summarise(total_count=n(), .groups = 'drop') %>% 
              as.data.frame()

str(data_age_alc)

# Plot the bar chart 
ggplot(data_age_alc, aes(x=Age_Alc, y=total_count)) + 
  geom_bar(stat = "identity")

```

```{r}
# Age when they started smoking
data_age_weed <- data %>% 
              group_by(Age_Weed) %>% 
              summarise(total_count = n(), .groups = 'drop') %>% 
              as.data.frame()

str(data_age_weed)

# Plot the bar chart 
ggplot(data_age_weed, aes(x = Age_Weed, y = total_count)) + 
  geom_bar(stat = "identity")

```

```{r}
# Age when they started smoking
data_age_sex <- data %>% 
              group_by(age_sex) %>% 
              summarise(total_count = n(), .groups = 'drop') %>% 
              as.data.frame()

str(data_age_sex)

# Plot the bar chart 
ggplot(data_age_sex, aes(x = age_sex, y = total_count)) + 
  geom_bar(stat = "identity")

```

```{r}
# Age when they started smoking
data_age_partner <- data %>% 
              group_by(multiple_partners) %>% 
              summarise(total_count = n(), .groups = 'drop') %>% 
              as.data.frame()

str(data_age_partner)

# Plot the bar chart 
ggplot(data_age_partner, aes(x = multiple_partners, y = total_count)) + 
  geom_bar(stat = "identity")

```

```{r}
# Age when they started smoking
data_Hrs_Sleep <- data %>% 
              group_by(Hrs_Sleep) %>% 
              summarise(total_count = n(), .groups = 'drop') %>% 
              as.data.frame()

str(data_Hrs_Sleep)

# Plot the bar chart 
ggplot(data_Hrs_Sleep, aes(x = Hrs_Sleep, y = total_count)) + 
  geom_bar(stat = "identity")

```


```{r}
# Age when they started smoking
data_physical_activity <- data %>% 
              group_by(physical_activity) %>% 
              summarise(total_count = n(), .groups = 'drop') %>% 
              as.data.frame()

str(data_physical_activity)

# Plot the bar chart 
ggplot(data_physical_activity, aes(x = physical_activity, y = total_count)) + 
  geom_bar(stat = "identity")

```

```{r}
library(corrplot)

M <- cor(data[, -c(7, 8, 9, 10)])

corrplot(M, method = 'number', addCoef.col = 1, number.cex = 0.5)
```

```{r}

data_grouped_2a <- data %>% 
              group_by(gender, multiple_partners) %>% 
              summarise(total_count1 = n(), .groups = 'drop') %>% 
              as.data.frame()

data_grouped_2b <- data %>% 
              group_by(gender, Age_Weed) %>% 
              summarise(total_count2 = n(), .groups = 'drop') %>% 
              as.data.frame()

ggplot(data_grouped_2a, aes(fill=multiple_partners, y=total_count1, x=multiple_partners)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~gender) +
    theme(legend.position="none") +
    xlab("")

ggplot(data_grouped_2b, aes(fill=Age_Weed, y=total_count2, x=Age_Weed)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~gender) +
    theme(legend.position="none") +
    xlab("")

data_grouped_2c <- data %>% 
              group_by(gender, Age_Alc) %>% 
              summarise(total_count3 = n(), .groups = 'drop') %>% 
              as.data.frame()

ggplot(data_grouped_2c, aes(fill=Age_Alc, y=total_count3, x=Age_Alc)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~gender) +
    theme(legend.position="none") +
    xlab("")



```

```{r}

data_grouped_3a <- data %>% 
              group_by(race, multiple_partners) %>% 
              summarise(total_count1 = n(), .groups = 'drop') %>% 
              as.data.frame()

data_grouped_3b <- data %>% 
              group_by(race, Age_Weed) %>% 
              summarise(total_count2 = n(), .groups = 'drop') %>% 
              as.data.frame()

ggplot(data_grouped_3a, aes(fill=multiple_partners, y=total_count1, x=multiple_partners)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~race) +
    theme(legend.position="none") +
    xlab("")

ggplot(data_grouped_3b, aes(fill=Age_Weed, y=total_count2, x=Age_Weed)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~race) +
    theme(legend.position="none") +
    xlab("")

data_grouped_3c <- data %>% 
              group_by(race, Age_Alc) %>% 
              summarise(total_count3 = n(), .groups = 'drop') %>% 
              as.data.frame()

ggplot(data_grouped_3c, aes(fill=Age_Alc, y=total_count3, x=Age_Alc)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~race) +
    theme(legend.position="none") +
    xlab("")

```

```{r}
data_grouped_4a <- data %>% 
              group_by(gender, suicide) %>% 
              summarise(total_count1 = n(), .groups = 'drop') %>% 
              as.data.frame()

data_grouped_4b <- data %>% 
              group_by(race, suicide) %>% 
              summarise(total_count2 = n(), .groups = 'drop') %>% 
              as.data.frame()

ggplot(data_grouped_4a, aes(fill=suicide, y=total_count1, x=suicide)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~gender) +
    theme(legend.position="none") +
    xlab("")

ggplot(data_grouped_4b, aes(fill=suicide, y=total_count2, x=suicide)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~race) +
    theme(legend.position="none") +
    xlab("")


```

```{r}
data_grouped_5a <- data %>% 
              group_by(gender, fight) %>% 
              summarise(total_count1 = n(), .groups = 'drop') %>% 
              as.data.frame()

data_grouped_5b <- data %>% 
              group_by(race, fight) %>% 
              summarise(total_count2 = n(), .groups = 'drop') %>% 
              as.data.frame()

ggplot(data_grouped_5a, aes(fill=fight, y=total_count1, x=fight)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~gender) +
    theme(legend.position="none") +
    xlab("")

ggplot(data_grouped_5b, aes(fill=fight, y=total_count2, x=fight)) + 
    geom_bar(position="dodge", stat="identity") +
    ggtitle("Studying ") +
    facet_wrap(~race) +
    theme(legend.position="none") +
    xlab("")


```




```{r}
loadPkg("ggplot2")
data$Age_Alc <- as.factor(data$Age_Alc)
ggplot(data, aes(x=Age_Alc, y=Hrs_Sleep)) + 
  geom_boxplot(outlier.shape = NA) +
  labs(title="Hours of Sleep By Age when First started Drinking")

loadPkg("ggplot2")
data$Age_Alc <- as.factor(data$Age_Alc)
ggplot(data, aes(x=Age_Alc, y=Hrs_Sleep)) + 
  geom_violin(outlier.shape = NA) +
  labs(title="Hours of Sleep By Age when First started Drinking")


```
```{r}
data$Age_Alc <- as.factor(data$Age_Alc)
ggplot(data, aes(x=Age_Alc, y=multiple_partners)) + 
  geom_boxplot(outlier.shape = NA) +
  labs(title="Number of Partners when First started Drinking")
```
```{r}
# select numeric variables
df <- dplyr::select_if(data, is.numeric)
# calculate the correlations
r <- cor(df, use="complete.obs")
round(r,2)
```


```{r}
data$fight1 <- recode(data$fight, '0' = 1, '1' = 0)
data$suicide1 <- recode(data$suicide, '0' = 1, '1' = 0)
```

## Including Plots

```{r}
summary(data)

data$Age_Alc <- as.numeric(data$Age_Alc)
```


You can also embed plots, for example:



```{r}
mod<-glm(formula = fight1 ~ Age_Weed + Age_Alc + age_sex + race , family = "binomial", data = data)
summary(mod)
plot(mod)
```


```{r}
mod2<-glm(formula = suicide ~ Age_Weed + Age_Alc + age_sex + Hrs_Sleep, family = "binomial", data = data)
summary(mod2)
```

```{r}
lm <- lm(Hrs_Sleep ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm)
xkabledply(lm, title = paste("Model :", format(formula(lm)) ) )
xkablevif(lm)
```

```{r}
lm1 <- lm(multiple_partners ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm1)
xkabledply(lm1, title = paste("Model :", format(formula(lm1)) ) )
```

```{r}
lm2 <- lm(physical_activity ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm2)
xkabledply(lm2, title = paste("Model :", format(formula(lm1)) ) )
```