---
title: "project101"
output: html_document
date: "2022-12-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ezids)
library(ggplot2)
library(plyr)
library(corrplot)
```

## SMART QUESTION

### Does the age at which adolescents start engaging in "deviant" behaviors predict their interpersonal, physical, and mental well-being? Furthermore, how does race influence interpersonal, physical, and mental well-being?


```{r cars}
data = read.csv("/Users/carriemagee/Downloads/v9.csv")
```

```{r}

```


```{r}
data$fight1 <- recode(data$fight, '0' = 1, '1' = 0)
data$suicide1 <- recode(data$suicide, '0' = 1, '1' = 0)
table(data$fight1,data$Age_Alc)
table(data$suicide1,data$Age_Alc)
table(data$drunk_driving1,data$Age_Alc)
```

## Including Plots

```{r}
summary(data)
data$sex <- as.factor(data$sex)
data$race <- as.factor(data$race)
```


You can also embed plots, for example:



```{r}
mod<-glm(formula = fight ~ Age_Weed + Age_Alc + age_sex + race , family = "binomial", data = data)
summary(mod)
```


```{r}
mod2<-glm(formula = suicide1 ~ Age_Weed + Age_Alc + age_sex + Hrs_Sleep, family = "binomial", data = data)
summary(mod2)
```

```{r}
table(data$drunk_driving1,data$Hrs_Sleep)
table(data$drunk_driving1,data$Age_Alc)
table(data$drunk_driving1,data$Age_Weed)
```
```{r}
data$race <- as.factor(data$race)
lm <- lm(Hrs_Sleep ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm)
xkabledply(lm, title = paste("Model :", format(formula(lm)) ) )
xkablevif(lm)
```

```{r}
lm1 <- lm(multiple_partners ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm1)
xkabledply(lm1, title = paste("Model :", format(formula(lm1)) ) )
```

```{r}
lm2 <- lm(physical_activity ~  Age_Alc + Age_Weed + age_sex + race, data=data)
summary(lm2)
xkabledply(lm2, title = paste("Model :", format(formula(lm1)) ) )
```